chore(TUP-30992)CVE: junit-4.11,4.13
Talend/studio-tools-se pull request #13
Opened 2021-04-07 06:20 UTC by jiezhang-tlnd

2021-04-13 02:24 UTC, bhe-talendbj requested changes

2021-04-13 02:24 UTC, bhe-talendbj commented on junit/META-INF/MANIFEST.MF
> + eexport`
why has a "`"?

2021-04-13 02:24 UTC, bhe-talendbj commented on junit/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib/junit-4.13.2.jar"/>
remove this line

2021-04-13 04:09 UTC, bhe-talendbj commented on junit/META-INF/MANIFEST.MF
> +Bundle-RequiredExecutionEnvironment: JavaSE-5
remove this? can you please help compare this with existing manifest.mf of 4.13.0?

2021-04-13 04:09 UTC, bhe-talendbj commented on junit/pom.xml
> +                                <Require-Capability>osgi.ee;filter:="(&amp;(osgi.ee=JavaSE)(version=1.5))"</Require-Capability>
version=1.8

2021-04-15 02:53 UTC, jiezhang-tlnd commented on junit/META-INF/MANIFEST.MF
> + eexport`
removed. thx

2021-04-15 02:55 UTC, bhe-talendbj approved these changes

2021-04-15 08:15 UTC, merged