chore(TUP- 40916): Studio issues if Java version is > Java 17
Talend/studio-tools-se pull request #41
Opened 2023-11-20 02:35 UTC by bhe-talendbj

https://jira.talendforge.org/browse/TUP-40916

2023-11-20 02:43 UTC, nrousseau requested changes

2023-11-20 02:43 UTC, nrousseau commented on studio-utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
> +                    "Maximal supported java version is " + JAVA_VERSION_MAXIMUM.toString()
1: Maximum supported (not Maximal..)
2: this will show maximum supported = 18, while we support 17 max

2023-11-20 02:52 UTC, bhe-talendbj commented on studio-utils/src/main/java/org/talend/utils/StudioKeysFileCheck.java
> +                    "Maximal supported java version is " + JAVA_VERSION_MAXIMUM.toString()
So quick, thank you.

2023-11-20 03:20 UTC, nrousseau submitted a review, later dismissed

2023-11-21 03:18 UTC, kjwang-talend approved these changes

2023-12-18 06:28 UTC, kjwang-talend approved these changes

2023-12-18 06:55 UTC, merged